// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 WulffTech

import * as vscode from 'vscode';
import { SubtitleMode } from '../core/subtitleText';

// categories and per-session metadata live in globalState, not workspaceState —
// session ids are uuids and unique across workspaces, and empty-window sessions
// don't belong to any workspace at all

const CATEGORIES_KEY = 'chatTags.categories';
const SESSION_META_KEY = 'chatTags.sessionMeta';
const BASELINE_KEY = 'chatTags.baselineAt';

export interface Category {
	id: string;
	name: string;
	// raw hex — inside our own webview there's no registered-colour requirement
	colour: string;
}

export interface SessionMeta {
	categoryId?: string;
	subtitle?: string;
	subtitleSource?: 'manual' | 'llm';
	subtitleUpdatedAt?: number;
	// which kind of line this is, so the automatic sweep regenerates what the session was
	// last given rather than whatever chatTags.subtitleMode happens to say today
	subtitleMode?: SubtitleMode;
	// shown instead of the title in the session file. the file itself is never written —
	// vs code holds it open and appends to it, so our record would be clobbered or worse
	title?: string;
	// only 'manual' guards against being regenerated by accident
	titleSource?: 'manual' | 'llm';
	// last time the user actually opened this session — anything newer needs attention
	seenAt?: number;
	// archived is ours, not vs code's. its own archived state lives in state.vscdb behind
	// the storage service, so we could write it but never read it back to reconcile
	archivedAt?: number;
}

// curated so every entry stays legible tinted on both light and dark backgrounds
export const PALETTE: ReadonlyArray<{ name: string; colour: string }> = [
	{ name: 'Blue', colour: '#3794ff' },
	{ name: 'Cyan', colour: '#29b8db' },
	{ name: 'Teal', colour: '#12a594' },
	{ name: 'Green', colour: '#3fb950' },
	{ name: 'Lime', colour: '#7ec242' },
	{ name: 'Amber', colour: '#d9a334' },
	{ name: 'Orange', colour: '#e08c3f' },
	{ name: 'Red', colour: '#e5534b' },
	{ name: 'Pink', colour: '#e05fa8' },
	{ name: 'Purple', colour: '#a371f7' },
	{ name: 'Indigo', colour: '#7a7af7' },
	{ name: 'Slate', colour: '#8b949e' }
];

function makeId(): string {
	// no crypto dependency needed; collisions only matter within one user's list
	return `cat_${Math.random().toString(36).slice(2, 10)}`;
}

export class TagStore {
	private readonly _onDidChange = new vscode.EventEmitter<void>();
	readonly onDidChange = this._onDidChange.event;

	constructor(private readonly memento: vscode.Memento) { }

	get categories(): Category[] {
		return this.memento.get<Category[]>(CATEGORIES_KEY, []);
	}

	category(id: string | undefined): Category | undefined {
		return id ? this.categories.find(entry => entry.id === id) : undefined;
	}

	private get allMeta(): Record<string, SessionMeta> {
		return this.memento.get<Record<string, SessionMeta>>(SESSION_META_KEY, {});
	}

	meta(sessionId: string): SessionMeta {
		return this.allMeta[sessionId] ?? {};
	}

	// without a baseline every pre-existing session would light up as unread on first
	// run, so first activation stamps 'now' and only later activity counts
	get baseline(): number {
		return this.memento.get<number>(BASELINE_KEY, 0);
	}

	async ensureBaseline(): Promise<void> {
		if (!this.baseline) {
			await this.memento.update(BASELINE_KEY, Date.now());
		}
	}

	needsAttention(sessionId: string, lastActivityAt: number): boolean {
		const seen = this.meta(sessionId).seenAt ?? this.baseline;
		return lastActivityAt > seen;
	}

	async markSeen(sessionId: string): Promise<void> {
		await this.patchMeta(sessionId, { seenAt: Date.now() });
	}

	async markAllSeen(sessionIds: string[]): Promise<void> {
		const meta = { ...this.allMeta };
		const now = Date.now();
		for (const id of sessionIds) {
			meta[id] = { ...meta[id], seenAt: now };
		}
		await this.memento.update(SESSION_META_KEY, meta);
		this._onDidChange.fire();
	}

	async createCategory(name: string, colour: string): Promise<Category> {
		const category: Category = { id: makeId(), name, colour };
		await this.memento.update(CATEGORIES_KEY, [...this.categories, category]);
		this._onDidChange.fire();
		return category;
	}

	async updateCategory(id: string, changes: Partial<Omit<Category, 'id'>>): Promise<void> {
		const next = this.categories.map(entry => entry.id === id ? { ...entry, ...changes } : entry);
		await this.memento.update(CATEGORIES_KEY, next);
		this._onDidChange.fire();
	}

	async deleteCategory(id: string): Promise<void> {
		await this.memento.update(CATEGORIES_KEY, this.categories.filter(entry => entry.id !== id));

		// drop the assignment too, or sessions keep pointing at a category that's gone
		const meta = { ...this.allMeta };
		for (const [sessionId, entry] of Object.entries(meta)) {
			if (entry.categoryId === id) {
				meta[sessionId] = { ...entry, categoryId: undefined };
			}
		}
		await this.memento.update(SESSION_META_KEY, meta);
		this._onDidChange.fire();
	}

	async setCategory(sessionId: string, categoryId: string | undefined): Promise<void> {
		await this.patchMeta(sessionId, { categoryId });
	}

	async setArchived(sessionId: string, archived: boolean): Promise<void> {
		await this.patchMeta(sessionId, { archivedAt: archived ? Date.now() : undefined });
	}

	// deleting a session leaves its metadata behind pointing at nothing, and the memento
	// is never swept otherwise
	async forget(sessionId: string): Promise<void> {
		const meta = { ...this.allMeta };
		if (!(sessionId in meta)) {
			return;
		}
		delete meta[sessionId];
		await this.memento.update(SESSION_META_KEY, meta);
		this._onDidChange.fire();
	}

	async setSubtitle(
		sessionId: string,
		subtitle: string | undefined,
		source: 'manual' | 'llm',
		mode?: SubtitleMode
	): Promise<void> {
		const kept = subtitle?.trim();
		await this.patchMeta(sessionId, {
			subtitle: kept ? kept : undefined,
			subtitleSource: kept ? source : undefined,
			subtitleUpdatedAt: kept ? Date.now() : undefined,
			// a hand-edit leaves the mode alone — the sweep skips manual subtitles anyway, and
			// clearing it would lose which kind of line the session had if it ever goes back
			subtitleMode: kept ? (mode ?? this.meta(sessionId).subtitleMode) : undefined
		});
	}

	async setTitle(sessionId: string, title: string | undefined, source: 'manual' | 'llm'): Promise<void> {
		const trimmed = title?.trim();
		await this.patchMeta(sessionId, {
			title: trimmed || undefined,
			titleSource: trimmed ? source : undefined
		});
	}

	private async patchMeta(sessionId: string, changes: Partial<SessionMeta>): Promise<void> {
		const meta = { ...this.allMeta };
		meta[sessionId] = { ...meta[sessionId], ...changes };
		await this.memento.update(SESSION_META_KEY, meta);
		this._onDidChange.fire();
	}

	dispose(): void {
		this._onDidChange.dispose();
	}
}
